### ISSUE TITLE
Tight coupling to infrastructure

### ISSUE THREAD

**Issue by brandonlamb** [fabricioepa/lab-hexagon-java#2]
core/application/src/main/java/com/ticketapp/core/application/repository/AccountRepository.java

You've tightly coupled an infrastructure concern to your core which should not contain frameworks or infrastructure things.

To create a MockAccountRepository concrete implementation means I would have to pull in JPA if I understand this. A JpaAccountRepository should be an adapter outside of core?

**Comment by fabricioepa** [comment]
Thank you Brandon for you feedback, your are right in your point of view, except that we should also consider what are the key project concerns and the context.
 
There should be no problem to choose JPA as a core concern of your project, since it is a framework to abstract persistence and make your core not dependent on any persistence implementation, if I do not want to spent effort creating and maintaining your persistence abstractions, I can easily rely on given JPA API which is only interface specs. 

You can also create a mock, e.g. using mockito, without need to launch any JPA implementation infrastructure.

Finally, If I would like to create my core independent of JPA framework (just like you described), I would create another level of abstraction to also make my core not dependent on frameworks which are already designed to give me productivity. This is not always a required practice, e.g.: for RAD project types.

Best Regards
